# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: tests
    silent: true
  tests:
    deps: [main_tests]
    aliases: [t]
  main_tests:
    cmds:
      - odin run erldin_tests
    silent: true
    sources:
      - ./erldin/*
      - ./erldin_tests/*
    aliases: [et]

interval: 250ms
